### ISSUE TITLE
Unit test examples

### ISSUE THREAD

**Issue by toniedzwiedz** [Knotx/knotx-extension-archetype#3]
Cover the classes in the generated project with unit tests.

Provide unit and integration test examples to serve as a source of good practices.

**Comment by tomaszmichalak** [comment]
I recommend to check this test: [io.knotx.knot.action.ActionKnotProxyVerticleTest](https://github.com/Cognifide/knotx/blob/master/knotx-knot/knotx-knot-action/src/test/java/io/knotx/knot/action/ActionKnotProxyVerticleTest.java)

**Comment by tomaszmichalak** [comment]
Fixed here: https://github.com/Knotx/knotx-extension-archetype/pull/11
